spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/currency_converter_db
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: info

secret:
  key:
    file:
      path: secret-key-file.txt
